services:
  app:
    build:
      context: .
    container_name: pdf_parser_app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./output:/app/output
      - paddlex_cache:/root/.paddlex # For PaddleX models
      - paddleocr_cache:/root/.paddleocr # For PaddleOCR models
    depends_on:
      - redis_service
    environment:
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
      - NVIDIA_VISIBLE_DEVICES=all # Makes all GPUs visible
      - PADDLE_ENFORCE_GPU=1 # Try to force Paddle to use GPU if available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  redis_service: # Name of the Redis service
    image: "redis:alpine" # Standard Redis image
    container_name: pdf_parser_redis
    ports:
      - "6380:6379" # Expose Redis on host port 6380 (to avoid conflict if you have local Redis on 6379)
                    # Container port is always 6379
    volumes:
      - redis_data:/data # Persist Redis data across restarts
    networks:
      - app_network

volumes:
  redis_data: # Define the named volume for Redis persistence
  paddlex_cache:
  paddleocr_cache:

networks:
  app_network: # Define a custom network
    driver: bridge